ansible_user: ansible
ansible_python_interpreter: /usr/bin/python3
server_admins:
  - name: Johannes Dewender
    user: dewendej
    mail: johannes.dewender@charite.de
  - name: Nils Bultjer
    user: bultjern
    mail: nils.bultjer@charite.de

proxy_env:
  http_proxy: "http://proxy.charite.de:8080/"
  https_proxy: "http://proxy.charite.de:8080/"
  ftp_proxy: "http://proxy.charite.de:8080/"
  gopher_proxy: ""
  socks_proxy: "http://proxy.charite.de:8080/"
  socks5_server: ""
  no_proxy: "localhost, 127.0.0.1"
time_zone: Europe/Berlin
ntp_server: time.charite.de
nagios_server_ip: 10.32.39.75
