proxy_env:
  http_proxy: "http://proxy.charite.de:8080/"
  https_proxy: "http://proxy.charite.de:8080/"
  ftp_proxy: "http://proxy.charite.de:8080/"
  gopher_proxy: ""
  socks_proxy: "http://proxy.charite.de:8080/"
  socks5_server: ""
  no_proxy: "localhost, 127.0.0.1"
proxy_host: "proxy.charite.de:141.42.5.215"
use_proxy: True

ntp_server: time.charite.de
nagios_server_ip: 10.32.39.75

mail_accounts:
  mb_ebiscinfo:
    user: mb-ebiscinfo
    pass: "{{ vault_mail_mb_ebiscinfo_pass }}"
    mail: info@ebisc.org
  mb_ebisccontact:
    user: mb-ebisccontact
    pass: "{{ vault_mail_mb_ebisccontact_pass }}"
    mail: ebisc-contact@charite.de

smtp_relay_account: "{{ mail_accounts.mb_ebiscinfo }}"
canonical_sender: "{{ smtp_relay_account.mail }}"

smtp_server: exchange-smtp.charite.de
relayhost: "{{ smtp_server }}"
smtp_port: 587
smtp_host: "exchange-smtp.charite.de:10.32.37.106"
