ansible_ssh_common_args: '-o ControlMaster=auto -o ControlPersist=30m -o StrictHostKeyChecking=no -o ProxyCommand="ssh -W %h:%p -q ubuntu@{{hostvars[groups.bastion[0]].ansible_ssh_host}}"'
ansible_ssh_user: core
ansible_python_interpreter: /home/core/bin/python
