proxy_env:
  http_proxy: ""
  https_proxy: ""
  ftp_proxy: ""
  gopher_proxy: ""
  socks_proxy: ""
  socks5_server: ""
  no_proxy: "localhost, 127.0.0.1"
use_proxy: False
ntp_server: ntp1.ptb.de

nagios_server_ip: 172.26.1.30

smtp_server: "172.26.1.10"
relayhost: "[{{ smtp_server }}]"
smtp_port: 25
smtp_host: "ber-mail.ibmt.fraunhofer.de:172.26.1.10" # actually not needed when given as IP above

canonical_sender: hpscreg-info@fraunhofer.de

hpscreg_host: "hpscreg.eu:172.26.2.20"
proxy_host: "{{ hpscreg_host }}"        # hack/workaround, as proxy_host is used in the build task
