#!/bin/bash

set -e

# set the following environment variables:
# OS_PASSWORD
# OS_AUTH_URL
# OS_USERNAME

freezer-agent \
  --path-to-backup /var/media \
  --container ims_media --backup-name media \

freezer-agent \
  --action admin --container $CONTAINER --remove-older-than 60 --backup-name media
