- name: "copy unit file "
  become: yes
  copy:
    dest: "/etc/systemd/system/nginx.service"
    src: "nginx.service"

- name: Create project directory
  file:
    path: "{{item}}"
    state: directory
    mode: "0750"
    owner: core
  become: yes
  with_items:
    - /var/projects/ebisc
    - /var/projects/ebisc/tls

- set_fact:
    tracker_ip: "{{hostvars[item].openstack.private_v4}}"
  with_items: "{{groups.tracker2}}"

- set_fact:
    ims_ip: "{{hostvars[item].openstack.private_v4}}"
  with_items: "{{groups.ims}}"

- set_fact:
    ims_staging_ip: "{{hostvars[item].openstack.private_v4}}"
  with_items: "{{groups.ims_staging}}"


- name: copy files
  template: dest=/var/projects/ebisc/tls/ebisc.org.key src=ebisc.org.key.j2
  notify: restart nginx
- name: copy files
  template: dest=/var/projects/ebisc/nginx.conf src=nginx.conf.j2
  notify: restart nginx
- name: copy files
  template: dest=/var/projects/ebisc/htpasswd src=htpasswd.j2
  notify: restart nginx

- name: copy files
  copy: "dest=/var/projects/ebisc/{{item}} src={{item}}"
  notify: restart nginx
  with_items:
    - Dockerfile-nginx
    - tls/ebisc.org.crt

- name: "enable unit"
  become: yes
  systemd:
    daemon_reload: yes
    enabled: yes
    name: "nginx.service"
    state: started

- name: build nginx image
  docker_image:
    path: /var/projects/ebisc
    dockerfile: Dockerfile-nginx
    name: ebisc/nginx
    state: present
    force: yes
  notify: restart nginx
