      
- name: Restore IMS database from latest backup in S3 object store
  hosts: ims,ims_staging
  tags: database
  roles:
    - postgres_restore

- name: Restore IMS media files from latest backup in S3 object store
  tags: media
  hosts: ims,ims_staging
  tasks:
    - name: "Start the duplicity restore service"
      become: yes
      systemd:
        daemon_reload: yes
        enabled: yes
        name: "duplicity-restore.service"
        state: started
    - name: "restart nginx and uwsgi"
      become: yes
      systemd:
        enabled: yes
        name: "{{item}}"
        state: restarted
      with_items:
        - ims-nginx.service
        - ims-uwsgi.service
