- name: Dump the database to localhost
  hosts: ims
  tags: database
  tasks:
    - name: Create a temp directory
      file:
        path: /tmp/db_dump
        state: directory
        mode: "0777"

    - name: Dump the current database
      environment:
        PGPASSWORD: "{{ postgresql_password }}"
        PGUSER: "{{ postgresql_user }}"
        PGDATABASE: "{{ postgresql_database }}"
      command: /var/projects/ebisc/scripts/dump_db.bash

    - name: fetch the backup
      fetch:
        dest: "{{ playbook_dir }}/"
        fail_on_missing: yes
        src: /tmp/db_dump/ebisc.sql.gz
        flat: yes

    - name: delete the remote backup
      become: yes
      file:
        path: /tmp/db_dump
        state: absent

- name: Dump the media files to localhost
  hosts: ims
  tags: media
  tasks:
    - name: synchronize media files
      become: yes
      synchronize:
        src: "{{ volume.mount }}/media"
        dest: "{{ playbook_dir }}/"
        delete: yes
        use_ssh_args: yes
        mode: pull
