- name: Dump the database to localhost
  hosts: ims
  tags: database
  tasks:
    - name: Dump the current database
      environment:
        PGPASSWORD: "{{ postgresql_password }}"
        PGUSER: "{{ postgresql_user }}"
        PGDATABASE: "{{ postgresql_database }}"
      command: /var/projects/ebisc/scripts/dump_db.bash

    - name: fetch the backup
      fetch:
        dest: "{{ playbook_dir }}"
        fail_on_missing: yes
        src: /tmp/ebisc.sql.gz
        flat: yes

    - name: delete the remote backup
      become: yes
      file:
        path: /tmp/ebisc.sql.gz
        state: absent

- name: Dump the media files to localhost
  hosts: ims
  tags: media
  tasks:
    - name: Tar the media files
      become: yes
      command: "tar -czf /tmp/media.tar.gz -C {{ volume.mount }} media"

    - name: fetch the backup
      fetch:
        dest: "{{ playbook_dir }}"
        fail_on_missing: yes
        src: /tmp/media.tar.gz
        flat: yes

    - name: delete the remote backup
      become: yes
      file:
        path: /tmp/media.tar.gz
        state: absent
