- name: Bootstrap coreos VMs ready to use ansible
  hosts: ims,ims_staging
  gather_facts: false
  roles:
    - coreos-bootstrap
      
- name: Set up IMS
  hosts: ims,ims_staging
  roles:
    - common
    - mnt_cinder
    - ims
