git_branch: master
postgresql_user: www
postgresql_database: ebisc

ims_role: production

volume:
  mount: /data01
  sub_directories:
    - name: postgres_data
      owner: 26
    - name: media
      owner: 1001
    - name: static
      owner: 1001
    - name: elasticsearch
      owner: 105
