- name: create mongo user
  user:
    name: "{{ mongo_user }}"
    system: yes
    create_home: no
  become: yes

- name: setup data directory
  file:
    path: "{{ data_dir }}/mongodb"
    state: directory
    owner: "{{ mongo_user }}"
    mode: u=rwX,g=rwX,o=
    recurse: yes
  become: yes

- name: Create repo directory
  file:
    path: /var/projects/tracker
    state: directory
    owner: "{{ ansible_user }}"
  become: yes

- name: Initialise git repo
  git:
    dest: /var/projects/tracker
    repo: https://github.com/EBiSC/ebisc_tracker_2.git
    accept_hostkey: yes
    update: yes
    version: master
  register: git

- name: build tracker webserver
  command: >
    docker build
    --pull
    --file=Dockerfile-webserver
    --build-arg=http_proxy=$http_proxy
    --build-arg=https_proxy=$https_proxy
    "--add-host={{ proxy_host }}"
    "--tag=ebisc/tracker-webserver:{{ git.after }}"
    .
  args:
    chdir: /var/projects/tracker
  register: docker_build

- name: retag tracker webserver image
  command: "docker tag ebisc/tracker-webserver:{{git.after}} ebisc/tracker-webserver:latest"

- name: restart webserver
  become: yes
  systemd:
    name: tracker-webserver.service
    state: restarted
  when: docker_build.changed

- name: build tracker
  command: >
    docker build
    --pull
    --file=Dockerfile-tracker
    --build-arg=http_proxy=$http_proxy
    --build-arg=https_proxy=$https_proxy
    "--add-host={{ proxy_host }}"
    "--tag=ebisc/tracker:{{ git.after }}"
    .
  args:
    chdir: /var/projects/tracker
  register: docker_build

- name: retag tracker image
  command: "docker tag ebisc/tracker:{{git.after}} ebisc/tracker:latest"
