- name: Create repo directory
  file:
    path: /var/projects/tracker
    state: directory
    owner: core
  become: yes

- name: Initialise git repo
  git:
    dest: /var/projects/tracker
    repo: https://github.com/EBiSC/ebisc_tracker_2.git
    accept_hostkey: yes
    update: yes
    version: master
  register: git

- name: build tracker webserver
  docker_image:
    path: /var/projects/tracker
    dockerfile: Dockerfile-webserver
    name: ebisc/tracker-webserver
    state: present
    tag: "{{git.after}}"
  register: docker_build

- name: retag image
  command: "docker tag ebisc/tracker-webserver:{{git.after}} ebisc/tracker-webserver:latest"

- name: restart webserver
  become: yes
  systemd:
    name: tracker-webserver.service
    state: restarted
  when: docker_build.changed

- name: build tracker
  docker_image:
    path: /var/projects/tracker
    dockerfile: Dockerfile-tracker
    name: ebisc/tracker
    state: present
    tag: "{{git.after}}"
  register: docker_build

- name: retag image
  command: "docker tag ebisc/tracker:{{git.after}} ebisc/tracker:latest"

- name: build db-backups-s3
  docker_image:
    path: /var/projects/tracker
    dockerfile: Dockerfile-db-backups-s3
    name: ebisc/mongodb-backups-s3
    state: present
    tag: "{{git.after}}"
  register: docker_build

- name: retag image
  command: "docker tag ebisc/mongodb-backups-s3:{{git.after}} ebisc/mongodb-backups-s3:latest"
