- name: install docker-py
  pip:
    executable: /home/core/bin/pip
    name: docker-py
    state: present
  tags: ['deploy', 'setup']

- include: setup.yml
  tags: ['setup']
- include: deploy.yml
  tags: ['deploy']
