
- name: create etcd2 security group
  os_security_group:
    name: etcd2
    description: "Opens all ports to the local subnet only. Protected from the world by the bastion"
    wait: yes

- name: configure etcd2 security group
  os_security_group_rule:
    security_group: etcd2
    state: present
    ethertype: "{{item.type}}"
    protocol: "{{item.protocol}}"
    remote_ip_prefix: "{{item.remote}}"
    direction: ingress
    port_range_min: "{{item.port_min | default(omit)}}"
    port_range_max: "{{item.port_max | default(omit)}}"
    wait: yes
  with_items: "{{security_rules.etcd2}}"

- name: configure network
  os_network:
    state: present
    name: "{{network}}"
    external: no
- name: configure subnet
  os_subnet:
    name: "{{subnet.name}}"
    network_name: "{{network}}"
    state: present
    cidr: "{{subnet.cidr}}"
    dns_nameservers: "{{subnet.dns_nameserver}}"
    enable_dhcp: "{{subnet.enable_dhcp}}"
    gateway_ip: "{{subnet.gateway_ip}}"
    wait: yes
- name: configure router
  os_router:
    state: present
    name: "{{router}}"
    interfaces:
      - "{{subnet.name}}"
    network: "{{external_network}}"
    wait: yes

