mongodb_user: ebisc_user
mongodb_database: ebisc
hpscreg_user: ebisctracker
ims_user: ebi
aws_access_key: DuiolYQGNGoAxNyYQMun
s3_host: s3.embassy.ebi.ac.uk

volume:
  name: tracker_mongodb_data
  mount: /mnt/cinder1
  sub_directories:
    - name: mongodb_data
      owner: 184
