mongodb_user: ebisc_user
mongodb_database: ebisc
swift_auth: https://extcloud03-ceilometer.ebi.ac.uk:8081/auth/v1.0
swift_user: swift-test
hpscreg_user: ebisctracker
ims_user: ebi

volume:
  name: tracker_mongodb_data
  mount: /mnt/cinder1
  sub_directories:
    - mongodb_data
