- name: install packages
  package:
    name: "{{ item }}"
  become: yes
  with_items: "{{ updates_packages }}"

- name: configure unattended-upgrades
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  become: yes
  notify: restart unattended-upgrades
  with_items:
    - src: 50unattended-upgrades.j2
      dest: /etc/apt/apt.conf.d/50unattended-upgrades
    - src: 20auto-upgrades.j2
      dest: /etc/apt/apt.conf.d/20auto-upgrades

- name: enable unattended-upgrades
  service:
    name: unattended-upgrades
    enabled: yes
    state: started
  become: yes
