
- name: "launch vm {{vm.name}}"
  os_server: 
    state: present
    name: "{{ vm.name }}"
    image: "{{image}}"
    flavor: "{{vm.flavor}}"
    network: "{{network}}"
    auto_ip: "{{ vm.auto_ip }}"
    security_groups: "{{ vm.security_group }}"
    wait: yes
    userdata: "{{lookup('template', 'coreos.cloud-config.yaml.j2')}}"

- name: "create cinder image {{ item.name }}  for {{ vm.name }}"
  os_volume:
    size: "{{item.size}}"
    display_name: "{{item.name}}"
    wait: yes
  with_items: "{{vm.volumes}}"

- name: "attach volume {{ item.name }}  to {{ vm.name }}"
  os_server_volume:
    server: "{{ vm.name }}"
    volume: "{{ item.name }}"
    wait: yes
  with_items: "{{vm.volumes}}"
