- name: set vm name
  set_fact:
    vm: "{{ vm_role.name }}-{{ vm_id }}"
    proxy: "{{vm_role.proxy}}"

#- name: debug printing cloud-config to /tmp/{{vm}}.cloudconfig
#  template:
#    src: worker.cloud-config.yaml.j2
#    dest: "/tmp/{{vm}}.cloudconfig"

- name: "launch vm {{vm}}"
  os_server: 
    state: present
    name: "{{ vm }}"
    image: "{{image}}"
    flavor: "{{flavor}}"
    network: "{{network}}"
    auto_ip: "{{ vm_role.auto_ip }}"
    security_groups: "{{ vm_role.security_group }}"
    wait: yes
    userdata: "{{lookup('template', 'worker.cloud-config.yaml.j2')}}"
