- set_fact:
    cluster_peers: "{{[]}}"
    bootstrap_cluster: true
- name: Test if a cluster already exists
  set_fact:
    bootstrap_cluster: false
    cluster_peers: "{{cluster_peers + [ 'https://' + hostvars[item].openstack.private_v4 ]}}"
  when: hostvars[item].openstack is defined and hostvars[item].openstack.name.find("worker") == 0
  with_items: "{{groups['all']}}"

- name: get discovery token
  uri:
    url: "https://discovery.etcd.io/new?size={{ [ cluster_size, max_etcd_servers ] | min }}"
    return_content: yes
  when: bootstrap_cluster
  register: discovery_token

- include: launch.yml
  vars:
    vm_id: "{{item}}"
    vm_role: "{{vm_roles.worker}}"
  with_sequence: count="{{ [ cluster_size, max_etcd_servers ] | min }}"

- include: launch.yml
  vars:
    vm_id: "{{item}}"
    vm_role: "{{vm_roles.proxy_worker}}"
  with_sequence: count="{{ [ cluster_size - max_etcd_servers, 0 ] | max }}"

- meta: refresh_inventory
