FROM debian:jessie

RUN apt-get update && \
    apt-get install -y ssmtp mailutils

COPY run-mailer /usr/local/bin/
RUN chmod 755 /usr/local/bin/run-mailer
RUN useradd -g root mailer
RUN chown mailer /etc/ssmtp/ssmtp.conf

CMD ["run-mailer"]
USER mailer
