FROM centos/postgresql-95-centos7

USER 0

ENV PYTHON_VERSION=3.4 \
  PATH=$HOME/.local/bin/:$PATH

RUN \
  yum install -y epel-release && \
  INSTALL_PKGS="rh-python34 rh-python34-python-devel rh-python34-python-setuptools rh-python34-python-pip gcc lzop pv" && \
  yum install -y --setopt=tsflags=nodocs --enablerepo=centosplus $INSTALL_PKGS && \
  rpm -V $INSTALL_PKGS

ENV ENABLED_COLLECTIONS="rh-postgresql95 rh-python34"

RUN localedef -c -i en_US -f UTF-8 en_US.UTF-8

USER 26
