#!/bin/bash

set -e

export WALE_LOG_DESTINATION=stdout,stderr
export PGUSER=postgres
export SWIFT_AUTH_VERSION=1

source "${CONTAINER_SCRIPTS_PATH}/common.sh"
set_pgdata

wal-e backup-push $PGDATA
wal-e delete --confirm retain 30
