FROM nginx:stable
COPY ./nginx.conf ./nginx-nocerts.conf /etc/nginx/
COPY ./vhosts-http.conf ./vhosts-https.conf /etc/nginx/conf.d/
COPY ./run-nginx /usr/local/bin/

RUN mkdir -p /var/log/nginx && \
  chmod g+w /var/cache/nginx /run /var/log/nginx && \
  mkdir -p /srv/ssl && \
  chown -R 1001:1001 /srv/ssl && \
  chmod 500 /srv/ssl && \
  chmod 755 /usr/local/bin/run-nginx

EXPOSE 8080
EXPOSE 8443

USER 1001
CMD ["run-nginx"]
