FROM certbot/certbot

COPY run-certbot /usr/local/bin/
RUN mkdir -p /etc/letsencrypt/live /usr/share/nginx/html/.well-known /var/log/letsencrypt /var/lib/letsencrypt && \
  chmod -R g+w /etc/letsencrypt /usr/share/nginx/html/.well-known /var/log/letsencrypt /var/lib/letsencrypt && \
  chmod 755 /usr/local/bin/run-certbot

ENTRYPOINT ["/bin/sh"]
CMD ["/usr/local/bin/run-certbot"]
USER 1001
