FROM nginx:stable
COPY ./nginx.conf /etc/nginx/nginx.conf

RUN chmod g+w /var/cache/nginx /run && \
  mkdir -p /srv/ssl && \
  chown -R 1001:1001 /srv/ssl && \
  chmod 400 /srv/ssl

EXPOSE 8080
EXPOSE 8443

USER 1001
