FROM nginx:stable
COPY ./nginx.conf /etc/nginx/nginx.conf

RUN mkdir -p /var/log/nginx && \
  chmod g+w /var/cache/nginx /run /var/log/nginx && \
  mkdir -p /srv/ssl && \
  chown -R 1001:1001 /srv/ssl && \
  chmod 500 /srv/ssl

EXPOSE 8080
EXPOSE 8443

USER 1001
