#!/bin/bash

certbot certonly \
  --webroot \
  --webroot-path /usr/share/nginx/html \
  --domain cells.ebisc.org \
  --domain cells-stage.ebisc.org \
  --domain www.cells.ebisc.org \
  --domain cell.ebisc.org \
  --domain www.cell.ebisc.org \
  --domain catalog.ebisc.org \
  --domain www.catalog.ebisc.org \
  --domain catalogue.ebisc.org \
  --domain www.catalogue.ebisc.org \
  --non-interactive \
  --agree-tos \
  --email vdc-internal@ebi.ac.uk \
  --preferred-challenges http-01  \
  --allow-subset-of-names \
  --expand \
  --keep-until-expiring


