#!/bin/bash

if [ -f /etc/letsencrypt/live/cells.ebisc.org/fullchain.pem -a -f /etc/letsencrypt/live/cells.ebisc.org/privkey.pem ]; then
  CONF=/etc/nginx/nginx.conf
else
  CONF=/etc/nginx/nginx-nocerts.conf
fi

exec nginx -c $CONF -g "daemon off;"
