FROM debian:jessie

RUN apt-get update && \
    apt-get install -y python-pip librsync-dev python-dev

ADD https://code.launchpad.net/duplicity/0.7-series/0.7.10/+download/duplicity-0.7.10.tar.gz /tmp
RUN pip install /tmp/duplicity-0.7.10.tar.gz boto && rm -f /tmp/duplicity-0.7.10.tar.gz

COPY run-duplicity-backup run-duplicity-restore /usr/local/bin/
RUN chmod 755 /usr/local/bin/run-duplicity-backup /usr/local/bin/run-duplicity-restore

CMD ["run-duplicity-backup"]
USER 1001
