- name: install mail transfer agent
  package:
    name: "{{ item }}"
  become: yes
  with_list: "{{ mail_packages }}"

- name: configure postfix
  template:
    src: "{{ item.name }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default('0644') }}"
    owner: root
    group: root
  no_log: "{{ item.no_log | default('no') }}"
  become: yes
  notify:
    - read new aliases
    - create databases
    - restart postfix
  with_items:
    - name: main.cf.j2
      dest: /etc/postfix/main.cf
    - name: sasl_passwd.j2
      dest: /etc/postfix/sasl_passwd
      mode: "0600"
      no_log: yes
      skip: "{{ 'True' if (smtp_relay_account == '') else 'False' }}"
    - name: sender_canonical.j2
      dest: /etc/postfix/sender_canonical
      skip: "{{ 'True' if (canonical_sender == '') else 'False' }}"
    - name: aliases.j2
      dest: /etc/aliases
  when: not item.skip|default(false)|bool

- name: enable postfix
  service:
    name: postfix
    enabled: yes
    state: started
  become: yes

- name: install systemd status mail service
  template:
    src: status-mail@.service.j2
    dest: "/etc/systemd/system/status-mail@.service"
  become: yes

- name: reload systemd files
  systemd:
    daemon_reload: yes
  become: yes

- meta: flush_handlers
