- name: install docker
  package:
    name: "{{ item }}"
    state: present
  become: yes
  with_list: "{{ docker_packages }}"

- name: enable docker
  service:
    name: "{{ docker_service }}"
    enabled: yes
    state: started
  become: yes

- name: add ansible user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  become: yes

- name: reset ssh connection (enable groups)
  meta: reset_connection

- name: add server admins to docker group
  user:
    name: "{{ item.user }}"
    groups: docker
    append: yes
  become: yes
  with_list: "{{ server_admins }}"

- meta: flush_handlers  # make sure we restart docker (proxy might have changed)

- name: prune docker
  command: docker system prune --volumes --force
