- include: hide_passfile.yml
- include: update_keys.yml
- include: proxy_setup.yml

- include: apt.yml

- include: time.yml
- include: nrpe.yml

- name: install common tools
  package:
    name: "{{ item }}"
    state: present
  become: yes
  with_items: "{{ common_packages }}"

- include: docker.yml

