FROM centos/postgresql-95-centos7

USER 0

RUN \
     yum install -y epel-release \
  && yum install -y python-pip python-devel gcc \
  && yum clean all

RUN \
  pip install gevent==1.0.2 && \
  pip install boto==2.38.0 && \
  pip install python-swiftclient==3.1.0 && \
  pip install wal-e==0.8.1

RUN \
     echo "wal_level = archive"   >> /usr/share/container-scripts/postgresql/openshift-custom-postgresql.conf.template \
  && echo "archive_mode = on"     >> /usr/share/container-scripts/postgresql/openshift-custom-postgresql.conf.template \
  && echo "archive_command = 'WALE_LOG DESTIONATION=stdout,stderr wal-e wal-push %p'" >> /usr/share/container-scripts/postgresql/openshift-custom-postgresql.conf.template \
  && echo "archive_timeout = 60"  >> /usr/share/container-scripts/postgresql/openshift-custom-postgresql.conf.template

USER 26
