- name: read new aliases
  command: newaliases
  become: yes

- name: create databases
  command: postmap /etc/postfix/{{ item.name }}
  become: yes
  with_list:
    - name: sasl_passwd
      skip: "{{ 'True' if smtp_relay_account == '' else 'False' }}"
    - name: sender_canonical
      skip: "{{ 'True' if canonical_sender == '' else 'False' }}"
  when: not item.skip|default(false)|bool

- name: restart postfix
  service:
    name: postfix
    state: restarted
  become: yes

