- name: Create project directories
  file:
    path: "{{item}}"
    state: directory
    owner: core
  become: yes
  with_items:
    - /var/projects/ebisc/ebisc-ims
    - /var/projects/ebisc/postgres
    - /var/projects/ebisc/duplicity
    - /var/projects/ebisc/scripts

- name: Initialise git repo
  git: dest=/var/projects/ebisc/ebisc-ims repo=git@github.com:DouglasConnect/ebisc.git accept_hostkey=yes update=yes version=streeter/docker
  register: git

- name: copy files
  copy: "dest=/var/projects/ebisc/{{ item }} src={{ item }}"
  with_items:
    - postgres/Dockerfile-postgres
    - postgres/run-backup-push
    - postgres/run-wal-push
    - duplicity/Dockerfile-duplicity
    - duplicity/run-duplicity-backup
    - duplicity/run-duplicity-restore

- name: copy scripts
  copy: "dest=/var/projects/ebisc/scripts/{{ item }} src=scripts/{{ item }} mode=0755"
  with_items:
    - dump_db.bash
    - import_db.bash

- name: build ims uwsgi
  docker_image:
    path: /var/projects/ebisc/ebisc-ims
    dockerfile: Dockerfile-uwsgi
    name: ebisc/ims-uwsgi
    state: present
    tag: "{{git.after}}"
  register: docker_build

- name: retag image
  command: "docker tag ebisc/ims-uwsgi:{{git.after}} ebisc/ims-uwsgi:latest"

- name: collectstatic and migrate django
  become: yes
  systemd:
    daemon_reload: yes
    name: ims-deploy.service
    state: restarted
  when: true

- name: restart uwsgi
  become: yes
  systemd:
    daemon_reload: yes
    name: ims-uwsgi.service
    state: restarted
  when: true

- name: build postgres image
  docker_image:
    path: /var/projects/ebisc/postgres
    dockerfile: Dockerfile-postgres
    name: ebisc/postgres
    state: present
    force: yes
  notify: restart postgres

- name: build ims nginx
  docker_image:
    path: /var/projects/ebisc/ebisc-ims
    dockerfile: Dockerfile-nginx
    name: ebisc/ims-nginx
    state: present
    tag: "{{git.after}}"
  register: docker_build

- name: retag image
  command: "docker tag ebisc/ims-nginx:{{git.after}} ebisc/ims-nginx:latest"

- name: restart nginx
  become: yes
  systemd:
    name: ims-nginx.service
    state: restarted
  when: docker_build.changed

- name: build duplicity
  docker_image:
    path: /var/projects/ebisc/duplicity
    dockerfile: Dockerfile-duplicity
    name: ebisc/duplicity
    state: present
    force: yes

- name: "enable unit"
  become: yes
  systemd:
    daemon_reload: yes
    enabled: yes
    name: "{{ item }}"
    state: started
  with_items:
    - ims-postgres.service
    - ims-uwsgi.service
    - ims-nginx.service
    - ims-elasticsearch.service
    - ims-updates.timer
    - postgres-backups.timer
    - duplicity-backups.timer
